Import("env")

env.AppendUnique(FRAMEWORKS=["AudioUnit", "OpenGL", "GLUT"])

env.Program("zephyr", [
  "battery.c",
  "cartridge.c",
  "cartridge-types/mbc1.c",
  "cartridge-types/mbc3.c",
  "cartridge-types/mbc5.c",
  "cartridge-types/romonly.c",
  "cpu.c",
  "gameboy.c",
  "interrupts.c",
  "joypad.c",
  "lcd.c",
  "lcdgl.c",
  "logging.c",
  "main.c",
  "memory.c",
  "sound/audiosamplebuffer.c",
  "sound/coreaudio.c",
  "sound/dutycycles.c",
  "sound/soundchannel1.c",
  "sound/soundchannel2.c",
  "sound/soundchannel3.c",
  "sound/soundchannel4.c",
  "sound/soundcontroller.c",
  "speedcontroller.c",
  "sprites.c",
  "timer.c",
  "timercontroller.c",
  "timing.c",
  "utils/os.c"
])