Import("env")

env.AppendUnique(FRAMEWORKS=["OpenGL", "GLUT"])

env.Program("gbemu1", [
  "battery.c",
  "cartridge.c",
  "cartridge-types/mbc1.c",
  "cartridge-types/romonly.c",
  "cpu.c",
  "gameboy.c",
  "interrupts.c",
  "lcd.c",
  "logging.c",
  "main.c",
  "memory.c",
  "sprites.c",
  "timer.c",
  "timing.c",
  "utils/os.c"
])